Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace SocialMedia.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

    }
}

Controllers/LoginController.cs
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SocialMedia.Models;

namespace SocialMedia.Controllers
{
    public class LoginController : Controller
    {
        private readonly DatabaseContext _dbContext;

        public LoginController(DatabaseContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login([FromForm] User model)
        {
            //Şifreyi MD5 ile şifrele
            var password = MD5Sifrele(model.Password);
            // Kullanıcıyı doğrula
            var user = _dbContext.Users.FirstOrDefault(u => u.UserName == model.UserName && u.Password == password);

            if (user != null)
            {
                if (user.Locked)
                {
                    ModelState.AddModelError(nameof(model.UserName), "User is locked");
                    ModelState.Remove("Email");
                    ModelState.Remove("LastName");
                    ModelState.Remove("FirstName");

                    return View(model);
                }

            }
            else
            {
                ModelState.AddModelError("", "Invalid username or password.");
                // Diğer hata mesajlarını temizle
                ModelState.Remove("Email");
                ModelState.Remove("Password");
                ModelState.Remove("FirstName");
                ModelState.Remove("LastName");
                ModelState.Remove("Username");
                return View();
            }
            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, user.UserId.ToString()),
                new Claim(ClaimTypes.Name, user.FullName ?? string.Empty),
                new Claim(ClaimTypes.Role,user.Role),
                new Claim("UserName", user.UserName)
            };

            ClaimsIdentity identity = new ClaimsIdentity(claims,
                CookieAuthenticationDefaults.AuthenticationScheme);

            ClaimsPrincipal principal = new ClaimsPrincipal(identity);
            HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
            // Kullanıcı girişi başarılı, işlemlere devam et
            return RedirectToAction("Post", "Post");
        }
        public string MD5Sifrele(string metin)
        {
            if (string.IsNullOrEmpty(metin))
                return string.Empty;

            using (var md5 = System.Security.Cryptography.MD5.Create())
            {
                var hash = md5.ComputeHash(System.Text.Encoding.UTF8.GetBytes(metin));
                return BitConverter.ToString(hash).Replace("-", "").ToLower();
            }
        }
       [Authorize]
        public IActionResult Logout()
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction(nameof(Login));
        }

    }
}

Controllers/ProfileController.cs
using Microsoft.AspNetCore.Mvc;
using SocialMedia.Models;
using System.Linq;
using System.Security.Claims;

namespace SocialMedia.Controllers
{
    public class ProfileController : Controller
    {
        private readonly DatabaseContext _dbContext;

        public ProfileController(DatabaseContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Profile()
        {
            int userId = int.Parse(User.FindFirst(c => c.Type == ClaimTypes.NameIdentifier).Value);
            User user = _dbContext.Users.Find(userId);

            ViewData["UserName"] = user.UserName;
            ViewData["FullName"] = user.FullName;

            return View();
        }

        [HttpPost]
        public IActionResult ProfileChangeUserName(string username)
        {
            if (ModelState.IsValid)
            {
                int userId = int.Parse(User.FindFirst(c => c.Type == ClaimTypes.NameIdentifier).Value);
                User user = _dbContext.Users.Find(userId);
                user.UserName = username;
                _dbContext.SaveChanges();

                ViewData["Message"] = "Username has been updated successfully.";
            }

            return RedirectToAction(nameof(Profile));
        }

        [HttpPost]
        public IActionResult ProfileChangePassword(string password)
        {
            if (ModelState.IsValid)
            {
                int userId = int.Parse(User.FindFirst(c => c.Type == ClaimTypes.NameIdentifier).Value);
                User user = _dbContext.Users.Find(userId);
                user.Password = MD5Sifrele(password);
                _dbContext.SaveChanges();

                ViewData["Message"] = "Password has been changed successfully.";
            }

            return RedirectToAction(nameof(Profile));
        }
        public string MD5Sifrele(string metin)
        {
            if (string.IsNullOrEmpty(metin))
                return string.Empty;

            using (var md5 = System.Security.Cryptography.MD5.Create())
            {
                var hash = md5.ComputeHash(System.Text.Encoding.UTF8.GetBytes(metin));
                return BitConverter.ToString(hash).Replace("-", "").ToLower();
            }
        }
        

       
    }



}

Controllers/RegisterController.cs
using Microsoft.AspNetCore.Mvc;
using SocialMedia.Models;

namespace SocialMedia.Controllers
{
    public class RegisterController : Controller
    {
        private readonly DatabaseContext _dbContext;

        public RegisterController(DatabaseContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var users = _dbContext.Users.ToList(); // Users tablosundan verileri çekiyoruz
            return View(users);
        }
      
        public IActionResult Register()
        {
            return View();
        }
        
        [HttpPost]
        public IActionResult Register([FromForm] User model)
        {
            if (_dbContext.Users.Any(c => c.Email.Equals(model.Email) && c.UserName.Equals(model.UserName)))
            {
                ModelState.AddModelError("", "This user is already registered.");
                return View(model);
            }
            
            if (ModelState.IsValid)
            {
                 // UTC zaman dilimindeki mevcut zamanı atar
                model.RegisterAt = DateTime.UtcNow;
                model.Password = MD5Sifrele(model.Password); // Şifreyi MD5 ile şifrele
                _dbContext.Users.Add(model);
                _dbContext.SaveChanges();
                return View("Feedback", model);
            }
            
            return View(model);
        }

        public string MD5Sifrele(string metin)
        {
            if (string.IsNullOrEmpty(metin))
                return string.Empty;

            using (var md5 = System.Security.Cryptography.MD5.Create())
            {
                var hash = md5.ComputeHash(System.Text.Encoding.UTF8.GetBytes(metin));
                return BitConverter.ToString(hash).Replace("-", "").ToLower();
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SocialMedia</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SocialMedia.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SocialMedia</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home"
                                asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Register"
                                asp-action="Index">Users</a>
                        </li>
                        @if (User.Identity.IsAuthenticated)
                        {


                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Profile"
                                    asp-action="Profile">@User.FindFirst("UserName").Value</a>
                            </li>

                           
                            if (User.IsInRole("admin"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Admin"
                                        asp-action="Index">Admin</a>
                                </li>
                            }
                             <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login"
                                    asp-action="Logout">Logout</a>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item ms-auto">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Login"
                                    asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Register"
                                    asp-action="Register">Register</a>
                            </li>

                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - SocialMedia - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>